content = '' 
content += \"import 'package:flutter/foundation.dart';\n\" 
content += \"import 'package:flutter/material.dart';\n\" 
content += \"import 'package:go_router/go_router.dart';\n\" 
content += \"import 'package:ui_kit/ninja_theme/ninja_theme.dart';\n\" 
content += \"import 'package:vocabulary/presentation/pages/vocabulary_page.dart';\n\" 
content += \"import 'package:reading/presentation/pages/reader_page.dart';\n\" 
content += \"import '../debug_overlay.dart';\n\" 
content += \"\n\" 
content += \"/// Desktop app root widget\n\" 
content += \"class WordNinjaDesktopApp extends StatelessWidget {\n\"  
content += \"  final GoRouter router;\n\"  
content += \"  const WordNinjaDesktopApp({super.key, required this.router});\n\"  
content += \"\n\"  
content += \"  @override\n\"  
content += \"  Widget build(BuildContext context) {\n\" 
content += \"    return MaterialApp.router(\n\"  
content += \"      title: 'Word Ninja',\n\"  
content += \"      debugShowCheckedModeBanner: false,\n\"  
content += \"      theme: NinjaTheme.light,\n\"  
content += \"      darkTheme: NinjaTheme.dark,\n\"  
content += \"      themeMode: ThemeMode.light,\n\"  
content += \"      routerConfig: router,\n\"  
content += \"      builder: kDebugMode ? _debugBuilder : null,\n\"  
content += \"    );\n\"  
content += \"  }\n\" 
content += \"\n\"  
content += \"  static Widget _debugBuilder(BuildContext context, Widget? child) {\n\"  
content += \"    return Stack(children: [\n\"  
content += \"      if (child != null) child,\n\"  
content += \"      Positioned(right: 16, bottom: 40, child: FloatingActionButton.small(\n\"  
content += \"        heroTag: '__debug_toggle__',\n\"  
content += \"        backgroundColor: DebugOverlay.isActive ? Colors.lightGreen : Colors.grey.shade400,\n\"  
content += \"        onPressed: DebugOverlay.toggleAll,\n\"  
content += \"        child: Icon(DebugOverlay.isActive ? Icons.visibility : Icons.visibility_off, size: 20),\n\"  
content += \"      )),\n\"  
content += \"    ]);\n\"  
content += \"  }\n\"  
content += \"}\n\" 
content += \"\n\"  
content += \"/// Desktop route paths\n\"  
content += \"class DesktopRoutes {\n\"  
content += \"  static const String home = '/';\n\"  
content += \"  static const String vocabulary = '/vocabulary';\n\"  
content += \"  static const String reading = '/reading';\n\"  
content += \"}\n\" 
content += \"\n\"  
content += \"GoRouter createDesktopRouter() {\n\"  
content += \"  return GoRouter(\n\"  
content += \"    initialLocation: DesktopRoutes.home,\n\"  
content += \"    routes: [\n\"  
content += \"      ShellRoute(\n\"  
content += \"        builder: (ctx, state, child) => DesktopShell(child: child),\n\"  
content += \"        routes: [\n\"  
content += \"          GoRoute(path: DesktopRoutes.home, builder: (ctx, state) => const _DesktopHome()),\n\"  
content += \"          GoRoute(path: DesktopRoutes.vocabulary, builder: (ctx, state) => const VocabularyPage()),\n\"  
content += \"          GoRoute(path: DesktopRoutes.reading, builder: (ctx, state) => const ReaderPage()),\n\"  
content += \"        ],\n\"  
content += \"      ),\n\"  
content += \"    ],\n\"  
content += \"  );\n\"  
content += \"}\n\" 
content += \"\n\"  
content += \"/// Desktop shell with left navigation rail\n\"  
content += \"class DesktopShell extends StatelessWidget {\n\"  
content += \"  final Widget child;\n\"  
content += \"  const DesktopShell({super.key, required this.child});\n\"  
content += \"\n\"  
content += \"  @override\n\"  
content += \"  Widget build(BuildContext context) {\n\"  
content += \"    return Row(children: [\n\"  
content += \"      NavigationRail(\n\"  
content += \"        selectedIndex: _calcIndex(context),\n\"  
content += \"        onDestinationSelected: (i) => _navigate(context, i),\n\" 
content += \"        labelType: NavigationRailLabelType.all,\n\"  
content += \"        leading: const Padding(\n\"  
content += \"          padding: EdgeInsets.symmetric(vertical: 8),\n\"  
content += \"          child: Text('\u{1F422}', style: TextStyle(fontSize: 24)),\n\"  
content += \"        ),\n\" 
content += \"        destinations: const [\n\"  
content += \"          NavigationRailDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home), label: Text('Home')),\n\"  
content += \"          NavigationRailDestination(icon: Icon(Icons.menu_book_outlined), selectedIcon: Icon(Icons.menu_book), label: Text('Vocab')),\n\"  
content += \"          NavigationRailDestination(icon: Icon(Icons.auto_stories_outlined), selectedIcon: Icon(Icons.auto_stories), label: Text('Reading')),\n\"  
content += \"        ],\n\" 
content += \"      ),\n\"  
content += \"      const VerticalDivider(width: 1),\n\"  
content += \"      Expanded(child: child),\n\"  
content += \"    ]);\n\"  
content += \"  }\n\" 
content += \"\n\"  
content += \"  int _calcIndex(BuildContext context) {\n\"  
content += \"    final uri = GoRouterState.of(context).uri.toString();\n\"  
content += \"    if (uri.startsWith(DesktopRoutes.vocabulary)) return 1;\n\"  
content += \"    if (uri.startsWith(DesktopRoutes.reading)) return 2;\n\"  
content += \"    return 0;\n\"  
content += \"  }\n\" 
content += \"\n\"  
content += \"  void _navigate(BuildContext context, int index) {\n\"  
content += \"    switch (index) {\n\"  
content += \"      case 0: context.go(DesktopRoutes.home);\n\"  
content += \"      case 1: context.go(DesktopRoutes.vocabulary);\n\"  
content += \"      case 2: context.go(DesktopRoutes.reading);\n\"  
content += \"    }\n\"  
content += \"  }\n\"  
content += \"}\n\" 
content += \"\n\"  
content += \"class _DesktopHome extends StatelessWidget {\n\"  
content += \"  const _DesktopHome();\n\"  
content += \"  @override\n\"  
content += \"  Widget build(BuildContext context) {\n\"  
content += \"    return const Center(child: Text('Word Ninja Desktop', style: TextStyle(fontSize: 24)));\n\"  
content += \"  }\n\"  
content += \"}\n\" 
import base64  
encoded = base64.b64encode(content.encode()).decode()  
print(encoded) 
