name: reading
description: Word Ninja reading training module
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  phosphor_flutter:
    git:
      url: https://github.com/subarnaPdl/phosphor_icons.git
      ref: main
  flutter:
    sdk: flutter
  core:
    path: ../core
  ui_kit:
    path: ../ui_kit
  ai:
    path: ../ai
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  vocabulary:
    path: ../vocabulary
  file_picker: ^11.0.2
  archive: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
